export const TICKERS = [
  "SPY", "QQQ", "IWM", "DIA", "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "TSLA", 
  "META", "BRK.B", "LLY", "V", "XOM", "UNH", "JPM", "WMT", "NVO", "MA", 
  "PG", "JNJ", "AVGO", "HD", "MRK", "ORCL", "CVX", "ABBV", "KO", "PEP", 
  "COST", "BAC", "ADBE", "CSCO", "MCD", "TMO", "CRM", "ACN", "NFLX", "AMD", 
  "LIN", "DHR", "ABT", "TMUS", "NKE", "DIS", "WFC", "TXN", "PM", "UPS", 
  "NEE", "MS", "BMY", "RTX", "INTC", "HON", "BA", "UNP", "AMGN", "IBM", 
  "LOW", "SPGI", "GE", "QCOM", "CAT", "AXP", "ISRG", "UBER", "NOW", "SYK", 
  "PFE", "AMAT", "GS", "ELV", "BKNG", "DE", "LMT", "SBUX", "BLK", "MDT", 
  "TJX", "ADP", "GILD", "MMC", "PLD", "VRTX", "LRCX", "C", "MDLZ", "ADI", 
  "ZTS", "REGN", "ISRG", "CI", "BSX", "FI", "ETN", "CB", "SLB", "MO", 
  "SO", "EOG", "BDX", "CME", "MU", "PANW", "KLAC", "EQIX", "SHW", "CSX", 
  "ITW", "CL", "PYPL", "SNPS", "CDNS", "ATVI", "APH", "WM", "EMR", "CMG", 
  "ICE", "FCX", "MCO", "HCA", "NXPI", "MAR", "MCK", "ORLY", "PSA", "CTAS", 
  "VLO", "FDX", "ECL", "PSX", "PGR", "ROP", "MPC", "APD", "GD", "OXY", 
  "GM", "TGT", "NSC", "MSI", "FTNT", "CARR", "HES", "MNST", "AZN", "ADSK", 
  "PAYX", "TRV", "SRE", "YUM", "AEP", "ROST", "MET", "AIG", "D", "ALL", 
  "O", "KMB", "TEL", "JCI", "EW", "BK", "PEG", "GWW", "CHTR", "IDXX", 
  "AFL", "FAST", "ED", "CTVA", "PCAR", "EXC", "KR", "XEL", "WMB", "KMI", 
  "BIIB", "STZ", "EA", "DHI", "VRSK", "DLTR", "ODFL", "LUV", "SYY", "DG", 
  "PPG", "ROK", "PRU", "HUM", "CNC", "ANET", "TSCO", "AMP", "AME", "FIS", 
  "PCG", "WEC", "CSGP", "AWK", "ON", "BKR", "HAL", "FANG", "DVN", "VRSN", 
  "CPT", "KEYS", "DFS", "GLW", "SBAC", "MTD", "WY", "GPN", "ULTA", "EFX", 
  "RMD", "TROW", "TTWO", "HIG", "DOV", "IRM", "XYL", "CBRE", "HPE", "ZBH", 
  "DAL", "FE", "CAH", "RJF", "MTB", "CHD", "WAB", "LYB", "BR", "EXR", 
  "DRI", "WAT", "ETR", "GRMN", "STE", "LHX", "NTAP", "TRGP", "HOLX", "F", 
  "TSN", "AES", "RF", "CINF", "STT", "OMC", "PKI", "COO", "VTR", "NTRS", 
  "EXPE", "IEX", "VICI", "K", "ATO", "AVY", "JBHT", "FSLR", "CNP", "CMS", 
  "PFG", "TXT", "CF", "BBY", "MAS", "MOH", "WRB", "NDSN", "J", "KDK", 
  "L", "LDOS", "FDS", "NDAQ", "MKC", "TYL", "BRO", "POOL", "SWK", "SYF", 
  "CE", "ALB", "PKG", "ESS", "AKAM", "SNA", "DGX", "WRK", "CBOE", "IP", 
  "CAG", "JKS", "ENPH", "SEDG", "FSLR", "RUN", "SPWR", "NOVA", "ARRY", 
  "NXT", "SHLS", "CSIQ", "DQ", "MAXN", "BE", "PLUG", "FCEL", "BLDP", 
  "GME", "AMC", "BB", "NOK", "PLTR", "SOFI", "RIVN", "LCID", "NIO", 
  "XPEV", "LI", "BABA", "JD", "PDD", "BIDU", "TCEHY", "BILI", "FUTU", 
  "TCOM", "HTHT", "ZTO", "BEKE", "EDU", "TAL", "GOTU", "IQ", "YY", "HUYA", 
  "DOYU", "MOMO", "WB", "BZ", "VIPS", "DADA", "YMM", "BOSS", "LX", "QFIN", 
  "FINV", "XYF", "LU", "FANH", "CNF", "HUIZ", "PUYI", "TIGR", "FUTU",
  "COIN", "MSTR", "MARA", "RIOT", "CLSK", "HIVE", "HUT", "BITF", "CIFR",
  "WULF", "IREN", "SDIG", "GREE", "ARBK", "BTBT", "ANY", "MIGI", "CORZ", 
  "BTC/USD", "ETH/USD", "SOL/USD" 
];
